[pytest]
# 测试用例路径
testpaths = .
#testpaths = ./testcases
# 测试用例命名和发现规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# 默认命令行参数-rA report All
addopts = -rA
# addopts = --cache-clear --tb=no 清空缓存
# 忽略的警告
# 跳过的目录
# 自定义标记
markers =
    smoke: 冒烟测试用例
    api: 接口测试用例
# 日志配置
# 超时设置
# 自动加载的插件
# 测试报告
